spring:
  application:
    name: OOsLibrary
  profiles:
    active: dev
# \uC2A4\uD504\uB9C1 \uD504\uB85C\uD544\uC744 \uD65C\uC6A9\uD574\uC11C \uAC1C\uBC1C \uD658\uACBD \uBCC4\uB85C \uC138\uD305 \uC124\uC815 \uAC00\uB2A5
---

# \uB85C\uCEEC \uAC1C\uBC1C\uD658\uACBD -> \uBC18\uB4DC\uC2DC \uC6D0\uACA9\uC5D0 \uC5F0\uACB0\uD558\uC9C0\uB9D0\uACE0 \uBCF8\uC778 \uB85C\uCEEC\uC5D0\uC11C \uAC1C\uBC1C\uD558\uACE0 \uD14C\uC2A4\uD2B8\uD560 \uAC83!!!
spring:
  config:
    activate:
      on-profile: dev

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create-drop


# \uBCF8\uC778 \uC120\uD638 \uD14C\uC2A4\uD2B8 DB \uC120\uD0DD\uD574\uC11C \uAC1C\uBC1C (H2 / MySQL)
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://[\uC8FC\uC18C]:3306/[DB schema]?serverTimezone=Asia/Seoul
#    username: [\uC720\uC800\uACC4\uC815]
#    password: '[\uBE44\uBC00\uBC88\uD638]'

#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
##            client-id: [\uB124\uC774\uBC84 \uAC1C\uBC1C\uC790 \uC571 \uD074\uB77C\uC774\uC5B8\uD2B8 \uC544\uC774\uB514]
##            client-secret: [\uB124\uC774\uBC84 \uAC1C\uBC1C\uC790 \uC571 \uD074\uB77C\uC774\uC5B8\uD2B8 \uC2DC\uD06C\uB9BF \uBC88\uD638]
#            scope:
#              - name
#              - email
#              - profile_image
#              - gender
#            client-name: Naver
#            authorization-grant-type: authorization_code # authorization-grant \uD0C0\uC785 \uC124\uC815
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver # \uB124\uC774\uBC84 \uC5B4\uD50C\uB9AC\uCF00\uC774\uC158\uC5D0 \uB4F1\uB85D\uD55C \uB9AC\uB2E4\uC774\uB809\uD2B8 uri
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response

  h2:
    console:
      enabled: true

#cloud:
#  aws:
#    s3:
#      endpoint: https://kr.object.ncloudstorage.com
#    credentials:
##      access-key: [ncp access key]
##      secret-key: [ncp secret key]
##      bucket: [ncp object storage bucket name]
#    region:
#      static: kr-standard
#      auto: false
#    stack:
#      auto: false

logging:
  level:
#    org:
#      springframework:
#        security: DEBUG
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.SQL: debug

mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.projectif.ooslibrary.mapper

---

spring:
  config:
    activate:
      on-profile: prod
