spring:
  application:
    name: OOsLibrary
  profiles:
    active: dev
# choose profile
---

# profile development -> dev
spring:
  config:
    activate:
      on-profile: dev

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create-drop


#  H2 / MySQL
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://[ip]:3306/[DB schema]?serverTimezone=Asia/Seoul
#    username: [username]
#    password: '[password]'

#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
##            client-id: [Naver Dev application client-id]
##            client-secret: [Naver Dev application client-secret]
#            scope:
#              - name
#              - email
#              - profile_image
#              - gender
#            client-name: Naver
#            authorization-grant-type: authorization_code # authorization-grant type
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver # redirect - uri
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response

  h2:
    console:
      enabled: true

#cloud:
#  aws:
#    s3:
#      endpoint: https://kr.object.ncloudstorage.com
#    credentials:
##      access-key: [ncp access key]
##      secret-key: [ncp secret key]
##      bucket: [ncp object storage bucket name]
#    region:
#      static: kr-standard
#      auto: false
#    stack:
#      auto: false

logging:
  level:
#    org:
#      springframework:
#        security: DEBUG
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.SQL: debug

mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.projectif.ooslibrary.mapper

---

spring:
  config:
    activate:
      on-profile: prod
